version: '3.8'

services:
  users-service:
    build: ./users
    ports:
      - "8001:8001"
    container_name: python_users_ms

  java-service:
    build: ./java-service
    ports:
      - "8002:8002"
    container_name: java_appointments_ms

  go-service:
    build: ./go-service
    ports:
      - "8003:8003"
    container_name: go_plans_ms

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - users-service
      - java-service
      - go-service
      
